schema_version: 1

context:
  version: "1.0.1"

package:
  name: zingo
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/z/zingo/zingo-${{ version }}.tar.gz
  sha256: 2359b024b80f03c23fc3e0250d40f6c07202fb949913e1b09a91edee2503d989

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - zingo = zingo.script:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - pytango

tests:
  - python:
      imports:
        - zingo
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - zingo --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: A command line tool for interacting with a Tango control system
  license: GPL-3.0-only
  license_file: LICENSE.txt
  homepage: https://gitlab.com/MaxIV/tools/zingo
  repository: https://gitlab.com/MaxIV/tools/zingo

extra:
  recipe-maintainers:
    - beenje
    - johanfforsberg
